### ISSUE TITLE
Post_ can not be resolved 

### ISSUE THREAD

**Issue by haokuang-zafin** [hantsy/angularjs-springmvc-sample#12]
Hi,
I am a beginner of JPA, after loading the project as maven in Eclipse. I got this error:
import com.hantsylabs.restexample.springmvc.domain.Post_;
I am not quite sure what's difference between  Post and Post_. Do I miss some dependencies? Thanks.

**Comment by hantsy** [comment]
Please read the README file and follow the steps to build the project.

**Comment by hantsy** [comment]
@haokuang-zafin It seems you know little about JPA.  Read the official Java EE tutorial please. 

[https://docs.oracle.com/javaee/7/tutorial/persistence-criteria001.htm#GJRIJ](https://docs.oracle.com/javaee/7/tutorial/persistence-criteria001.htm#GJRIJ)

As a Java backend( Java EE) developer, you should know all the knowledge in this tutorial.
