### ISSUE TITLE
PostSpecifications.java文件里找不到类Post_

### ISSUE THREAD

**Issue by XIRALIP** [hantsy/angularjs-springmvc-sample#16]
angularjs-springmvc-sample/src/main/java/com/hantsylabs/restexample/springmvc/repository/PostSpecifications.java 文件里用Post_的意图是什么？import com.hantsylabs.restexample.springmvc.domain.Post_;这个包里找不到。。。

**Comment by hantsy** [comment]
explained in #3  and #12
