### ISSUE TITLE
缺少文件:Post_.java和User_.java

### ISSUE THREAD

**Issue by oneingfw** [hantsy/angularjs-springmvc-sample#3]
repository/PostSpecifications.java引用了Post_,
repository/UserSpecifications.java引用了User_

但是domain下并没有这两个文件。
是我找开的方式不对？

**Comment by hantsy** [comment]
这是自动生成的 JPA 的 Metadata，IDE（NetBeans，Eclipse） 都会自动识别APT，Maven 命令编译一下也可以出来了。

**Comment by hantsy** [comment]
Not a bug, close
