### ISSUE TITLE
error mvn tomcat7:run

### ISSUE THREAD

**Issue by puyide** [hantsy/angularjs-springmvc-sample#4]
INFO] Total time: 10.196 s
[INFO] Finished at: 2015-08-05T17:26:31+08:00
[INFO] Final Memory: 13M/102M
[INFO] ------------------------------------------------------------------------
[ERROR] No plugin found for prefix 'spring-boot' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (/root/.m2/repository), io.spring.repo.maven.release (http://repo.spring.io/release/), io.spring.repo.maven.milestone (http://repo.spring.io/milestone/), central (https://repo.maven.apache.org/maven2)] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/NoPluginFoundForPrefixException

**Comment by hantsy** [comment]
Please confirm you are running `mvn tomcat7:run` in the root folder and you are staying on `master`.

```
  git branch // run this command to confirm which branch you located.
```

 The error indicates the missing of the Spring boot maven plugin which is **not available** in the `master` branch at all.

BTW, I have changed the project structure, and moved the `boot` branch into a new project, [AngularJS SpringMVC Sample Boot](https://github.com/hantsy/angularjs-springmvc-sample).

**Comment by hantsy** [comment]
Just confirmed on my local system, it works.

Good luck.
