### ISSUE TITLE
Missing angular-bootstrap.js and angular-bootstrap.css

### ISSUE THREAD

**Issue by daparthimanu** [hantsy/angularjs-springmvc-sample#5]
Hi Hantsy,

I'm new to AngularJs and I'm trying your tutorial as my first example, I'm having compilation errors in main.html file its missing angular-bootstrap.js and angular-bootstrap.css files. Could you please add them.

Thanks 
your student

**Comment by hantsy** [comment]
They are generated by the wro plugin when build the project. 

Please follow steps in  [README](https://github.com/hantsy/angularjs-springmvc-sample/blob/master/README.md). 

Closed, this is not a bug at all.
