### ISSUE TITLE
I'v tried many ways to solve the problem that when I use IDEA maven tomcat plugin always authentication required for username and password

### ISSUE THREAD

**Issue by Zerowxm** [hantsy/angularjs-springmvc-sample#7]
I set user name and password in configuration and in app.properties but it does not work please help

**Comment by hantsy** [comment]
What is your problem?

**Comment by hantsy** [comment]
@Zerowxm 
1. Please confirm u have read the Readme.md file.
2. Learn how to ask a question. 
   http://stackoverflow.com/help/how-to-ask

**Comment by Zerowxm** [comment]
yes i can open your index.html but when i login ,a dialog alert me of authentication  required

**Comment by Zerowxm** [comment]
localhost:[port]  required username and password to move on

**Comment by hantsy** [comment]
Just confirmed, it works well.

![image 2](https://cloud.githubusercontent.com/assets/854520/11748691/6e169338-a064-11e5-8261-d91434dfc4af.png)

Follow the steps in [README.md](https://github.com/hantsy/angularjs-springmvc-sample/blob/master/README.md) file. 

Thanks.
